server:
  port: 443
  ssl:
    key-store: ${WEBLOG_SSL_KEY_STORE}
    key-password: ${WEBLOG_SSL_KEY_PASSWORD}
    key-store-type: PKCS12
    key-alias: 1

spring:
  datasource:
    url: jdbc:mysql:///weblog?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: ASD2100150

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*.xml

logging:
  level:
    root: info

#pagehelper:
#  offsetAsPageNum: true
#  rowBoundsWithCount: true
#  reasonable: true
