server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql:///weblog?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: ASD2100150

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
    - classpath:/mapper/*.xml

logging:
  level:
    root: debug

pagehelper:
  offsetAsPageNum: true
  rowBoundsWithCount: true
  reasonable: true